// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ImageListerExpansion allows custom methods to be added to
// ImageLister.
type ImageListerExpansion interface{}

// ImageNamespaceListerExpansion allows custom methods to be added to
// ImageNamespaceLister.
type ImageNamespaceListerExpansion interface{}
