apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: defaulting.webhook.shipwright-image.knative.dev
  labels:
    samples.knative.dev/release: devel
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook
      namespace: shipwright-image
  failurePolicy: Fail
  name: defaulting.webhook.shipwright-image.knative.dev
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.webhook.shipwright-image.knative.dev
  labels:
    samples.knative.dev/release: devel
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook
      namespace: shipwright-image
  failurePolicy: Fail
  name: validation.webhook.shipwright-image.knative.dev
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: config.webhook.shipwright-image.knative.dev
  labels:
    serving.knative.dev/release: devel
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: webhook
      namespace: shipwright-image
  failurePolicy: Fail
  name: config.webhook.shipwright-image.knative.dev
  namespaceSelector:
    matchExpressions:
    - key: samples.knative.dev/release
      operator: Exists
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-certs
  namespace: shipwright-image
  labels:
    samples.knative.dev/release: devel
# The data is populated at install time.
