// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/imjasonh/image/pkg/client/clientset/versioned/typed/image/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeImageV1alpha1 struct {
	*testing.Fake
}

func (c *FakeImageV1alpha1) Images(namespace string) v1alpha1.ImageInterface {
	return &FakeImages{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeImageV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
